name: moqat7a
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  chat_package: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - lib/assets/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-VariableFont_slnt,wght.ttf
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 500

        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700

        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 300
    - family: Almarai
      fonts:
        - asset: fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: fonts/Almarai/Almarai-Regular.ttf
          weight: 500
        - asset: fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 900
